<a href="https://colab.research.google.com/github/AleixoCodes/Machine-Learning-com-dados-do-Spotify/blob/main/Analise_dos_dados_com_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Analisando dados do Spotify e prevendo músicas populares com Machine Learning**

## **Importando Dados**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the '-spotify-tracks-dataset' dataset.
Path to dataset files: /kaggle/input/-spotify-tracks-dataset

In [3]:
dadosMusicais = pd.read_csv("/kaggle/input/-spotify-tracks-dataset/dataset.csv")
dadosMusicais

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

### Traduzindo dataframe

In [20]:
dadosMusicais.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')

listaEN = ['track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre']

listaPT = ['track_id', 'artistas', 'nome_do_album', 'nome_da_musica',
       'popularidade', 'duracao_ms', 'explicito', 'dancabilidade', 'energia',
       'chave', 'volume', 'modo', 'falada', 'acustica',
       'instrumental', 'ao_vivo', 'positividade', 'tempo', 'tempo_de_assinatura',
       'genero_musical']

dadosMusicais.columns = listaPT
dadosMusicais.head()

,track_id,artistas,nome_do_album,nome_da_musica,popularidade,duracao_ms,explicito,dancabilidade,energia,chave,volume,modo,falada,acustica,instrumental,ao_vivo,positividade,tempo,tempo_de_assinatura,genero_musical
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

## **Analisando estatísticas dos dados**

In [21]:
dadosMusicais.shape

(114000, 20)

In [22]:
dadosMusicais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   track_id             114000 non-null  object
 1   artistas             113999 non-null  object
 2   nome_do_album        113999 non-null  object
 3   nome_da_musica       113999 non-null  object
 4   popularidade         114000 non-null  int64
 5   duracao_ms           114000 non-null  int64
 6   explicito            114000 non-null  bool
 7   dancabilidade        114000 non-null  float64
 8   energia              114000 non-null  float64
 9   chave                114000 non-null  int64
 10  volume               114000 non-null  float64
 11  modo                 114000 non-null  int64
 12  falada               114000 non-null  float64
 13  acustica             114000 non-null  float64
 14  instrumental         114000 non-null  float64
 15  ao_vivo              114000 non-null  float64
 16  positividade         114000 non-null  float64
 17  tempo                114000 non-null  float64
 18  tempo_de_assinatura  114000 non-null  int64
 19  genero_musical       114000 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 16.6+ MB

In [23]:
dadosMusicais.describe()

,popularidade,duracao_ms,dancabilidade,energia,chave,volume,modo,falada,acustica,instrumental,ao_vivo,positividade,tempo,tempo_de_assinatura
count,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [25]:
# Analisando valores nulos
dadosMusicais.isnull().sum()

track_id               0
artistas               1
nome_do_album          1
nome_da_musica         1
popularidade           0
duracao_ms             0
explicito              0
dancabilidade          0
energia                0
chave                  0
volume                 0
modo                   0
falada                 0
acustica               0
instrumental           0
ao_vivo                0
positividade           0
tempo                  0
tempo_de_assinatura    0
genero_musical         0
dtype: int64

In [34]:
ranking_popularidade = dadosMusicais[['artistas','popularidade']]
ranking_popularidade = ranking_popularidade.groupby('artistas').mean().sort_values(by='popularidade', ascending=False).reset_index()
ranking_popularidade.head(7)

                     artistas  popularidade
0        Sam Smith;Kim Petras         100.0
1            Bizarrap;Quevedo          99.0
2               Manuel Turizo          98.0
3  Bad Bunny;Chencho Corleone          97.0
4     Bad Bunny;Bomba Estéreo          94.5
5                        Joji          94.0
6                     Beyoncé          93.0